# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:

  mysql:
    image: mysql:8
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - my-net
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      # Ниже 2 строки для подключения кастомного конфига
      # - ./images/mysql/start.sh:/etc/mysql/start.sh
      # - ./images/mysql/conf.d/zz-1-custom.cnf:/etc/mysql/conf.d/zz-1-custom.cnf
    hostname: web-mysql
    domainname: dev.lan
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_ALL_TABLES
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      # - PMA_ARBITRARY=1  
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - my-net  
    depends_on:
      - mysql 

  pybot:
    build: ./
    container_name: pybot
    hostname: pybot
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    networks:
      - my-net 
    command: python bot.py demo start --custom demo --log_level INFO 
    depends_on:
      - mysql 

networks:
    my-net:
        driver: bridge
